### ISSUE TITLE
How can I write data ?

### ISSUE THREAD

**Issue by jpalbertini** [freand76/usbip-server#1]
Hi

I need to simulate a usb connection for some unit tests. Currently, with the BulkIO example, I'm able to open the virtual device and read (empty) data. But I can't figure out how I can write data on the bus synchroneously and I can't figure out how/when the HIDMouse sends it's own data...

Is there an example somewhere ?

**Comment by freand76** [comment]
Hi,

It has been a while since I worked with this and I never really found a use for it myself. I Just did it as a project to educate myself a little bit :-)

When I run the the following:

In terminal window 1:
> sudo modprobe vhci-hcd
> .x86/BulkIO -v

In terminal window 2:
> sudo usbip attach -b 1-1 -r localhost
> sudo tools/test-bulkio.py

I have output in both windows.... the output in window 1 will be from the device side, the output in window 2 will be n the host side. The device prints the data received on the USB bulk when written to. The device also prints info when being read from.

The python script test-bulkio.py will send data to the device and read data from the device.
It should work out of the box and you can probably get the python script to run without sudo if you setup udev rules for the device.

Regarding the HidMouse and when it sends data is a more complicated question. When a USB HID device is connected to the PC, the PC will start making requests over USB. The USB is always polled, the device cannot initiate a data transfer by itself, it is always the host (PC) that is asking for data.

I have learned a lt about USB (including low level signalling) in the following site: https://www.beyondlogic.org/usbnutshell/usb1.shtml

I have updated the repo a little bit regarding the output from BulkIO

If you explain a little bit more on what you would like to achieve I might be able to point you in the correct direction :-)
(And maybe write an example that could help you and others)

Regards
/Fredrik
